### ISSUE TITLE
Nest can't resolve dependencies of the AuthGuard (?, KEYCLOAK_CONNECT_OPTIONS, KEYCLOAK_LOGGER, KEYCLOAK_MULTITENANT_SERVICE, Reflector). Please make sure that the argument KEYCLOAK_INSTANCE at index [0] is available in the CategoryModule context.

### ISSUE THREAD

**Issue by mohamedsabith** [ferrerojosh/nest-keycloak-connect#175]
Error: Nest can't resolve dependencies of the AuthGuard (?, KEYCLOAK_CONNECT_OPTIONS, KEYCLOAK_LOGGER, KEYCLOAK_MULTITENANT_SERVICE, Reflector). Please make sure that the argument KEYCLOAK_INSTANCE at index [0] is available in the CategoryModule context.

Potential solutions:
- Is CategoryModule a valid NestJS module?
- If KEYCLOAK_INSTANCE is a provider, is it part of the current CategoryModule?
- If KEYCLOAK_INSTANCE is exported from a separate @Module, is that module imported within CategoryModule?
  @Module({
    imports: [ /* the Module containing KEYCLOAK_INSTANCE */ ]
  })

    at Injector.lookupComponentInParentModules (C:\Users\User\Desktop\be-core\node_modules\@nestjs\core\injector\injector.js:247:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Injector.resolveComponentInstance (C:\Users\User\Desktop\be-core\node_modules\@nestjs\core\injector\injector.js:200:33)
    at resolveParam (C:\Users\User\Desktop\be-core\node_modules\@nestjs\core\injector\injector.js:120:38)
    at async Promise.all (index 0)
    at Injector.resolveConstructorParams (C:\Users\User\Desktop\be-core\node_modules\@nestjs\core\injector\injector.js:135:27)
    at Injector.loadInstance (C:\Users\User\Desktop\be-core\node_modules\@nestjs\core\injector\injector.js:61:13)
    at Injector.loadInjectable (C:\Users\User\Desktop\be-core\node_modules\@nestjs\core\injector\injector.js:84:9)
    at C:\Users\User\Desktop\be-core\node_modules\@nestjs\core\injector\instance-loader.js:80:13
    at async Promise.all (index 0)

**Comment by patostickar** [comment]
Hi Mohamed, I have had this error before, and it happens when you don't import the Keycloak module in the AppModule if you use the global guards, or in the corresponding module if you use it in a specific one.

**Comment by daryaego** [comment]
I have the almost same error, but for 4th argument
Here is error text
`Nest can't resolve dependencies of the AuthGuard (KEYCLOAK_INSTANCE, KEYCLOAK_CONNECT_OPTIONS, KEYCLOAK_LOGGER, KeycloakMultiTenantService, ?). Please make sure that the argument Reflector at index [4] is available in the AppModule context.

Potential solutions:
- Is AppModule a valid NestJS module?
- If Reflector is a provider, is it part of the current AppModule?
- If Reflector is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing Reflector */ ]
  })

Error: Nest can't resolve dependencies of the AuthGuard (KEYCLOAK_INSTANCE, KEYCLOAK_CONNECT_OPTIONS, KEYCLOAK_LOGGER, KeycloakMultiTenantService, ?). Please make sure that the argument Reflector at index [4] is available in the AppModule context.

Potential solutions:
- Is AppModule a valid NestJS module?
- If Reflector is a provider, is it part of the current AppModule?
- If Reflector is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing Reflector */ ]
  })`
  
Whould be happy to hear some suggestions to fix it
