### ISSUE TITLE
Extending AuthGuard  Cannot read properties of undefined (reading 'getAllAndOverride')

### ISSUE THREAD

**Issue by chmoder** [ferrerojosh/nest-keycloak-connect#186]
Version: "nest-keycloak-connect": "1.10.0"

When extending `AuthGuard` the reflector instance appears to be empty object.  All the other arguments look correct.  Am I extending the class properly.

May be related to https://github.com/ferrerojosh/nest-keycloak-connect/issues/183?

```TypeScript
@Injectable()
export class SomethingOrKeycloakAuthGuard
  extends AuthGuard
  implements CanActivate
{
  constructor(
    singleTenant: KeycloakConnect.Keycloak,
    keycloakOpts: KeycloakConnectConfig,
    logger: Logger,
    multiTenant: KeycloakMultiTenantService,
    reflector: Reflector
  ) {
    console.log('test');
    console.log(reflector1);
    super(singleTenant, keycloakOpts, logger, multiTenant, reflector);
  }
```

Output:
test
Reflector {}

```
err: {
      "type": "Error",
      "message": "Cannot read properties of undefined (reading 'getAllAndOverride')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'getAllAndOverride')
              at DjangoOrKeycloakAuthGuard.<anonymous> (/Users/thomas/development/gitlab/platform/node_modules/nest-keycloak-connect/dist/guards/auth.guard.js:70:50)
              at Generator.next (<anonymous>)
              at /Users/thomas/development/gitlab/platform/node_modules/nest-keycloak-connect/dist/guards/auth.guard.js:43:71
              at new Promise (<anonymous>)
              at __awaiter (/Users/thomas/development/gitlab/platform/node_modules/nest-keycloak-connect/dist/guards/auth.guard.js:39:12)
              at DjangoOrKeycloakAuthGuard.canActivate (/Users/thomas/development/gitlab/platform/node_modules/nest-keycloak-connect/dist/guards/auth.guard.js:69:16)
              at DjangoOrKeycloakAuthGuard.canActivate (/Users/thomas/development/gitlab/platform/dist/apps/api/main.js:8803:55)
              at GuardsConsumer.tryActivate (/Users/thomas/development/gitlab/platform/node_modules/@nestjs/core/guards/guards-consumer.js:15:34)
              at canActivateFn (/Users/thomas/development/gitlab/platform/node_modules/@nestjs/core/router/router-execution-context.js:135:59)
              at /Users/thomas/development/gitlab/platform/node_modules/@nestjs/core/router/router-execution-context.js:42:37
    }
```

**Comment by akalana** [comment]
Hey, @chmoder same issue happens to me as well. Any update regarding this?
