### ISSUE TITLE
ValidateAccessToken Error:  Error: 404:Not Found

### ISSUE THREAD

**Issue by dulkith** [ferrerojosh/nest-keycloak-connect#21]
I got error when access this end point.

> @Controller()
> @Resource('test')
> export class AppController {
>     constructor(private readonly appService: AppService) {
>     }
> 
>     @Get('login')
>     @Roles('master:admin', 'Hello:admin', 'admin')
>     @AllowAnyRole()
>     async getHello() {
>         return true;
>     }
> 

`validateAccessToken Error:  Error: 404:Not Found
    at ClientRequest.<anonymous> (/Users/HELLO/Documents/GitHub/MY_COM/app-service/node_modules/keycloak-connect/middleware/auth-utils/grant-manager.js:523:23)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at Socket.socketOnData (_http_client.js:469:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)`

**Comment by joravkumar** [comment]
@dulkith 
I'm facing the same issue. Can you please describe how you solve this error?

Thanks in advance.
