### ISSUE TITLE
TypeError when extending AuthGuard

### ISSUE THREAD

**Issue by ashleyww93** [ferrerojosh/nest-keycloak-connect#84]
**_Reusing a previous non-issue I created today by mistake._**

I am trying to extend AuthGuard so that I can get access to more information about my Authenticated User in my GraphQL queries.

Basically, I want to be able to return objects that are owned by my tenant (each user is a tenant in my system).

I have tried the following code:

```
import {
    KEYCLOAK_INSTANCE,
    KEYCLOAK_CONNECT_OPTIONS,
    KEYCLOAK_LOGGER,
    AuthGuard,
    RoleMatchingMode,
    Roles,
} from 'nest-keycloak-connect';
import { applyDecorators, CanActivate, ExecutionContext, Inject, Injectable, Logger, UseGuards } from '@nestjs/common';
import { Reflector } from '@nestjs/core';
import { extractRequest } from 'nest-keycloak-connect/util';
import { GqlExecutionContext } from '@nestjs/graphql';
import { ExecutionContextHost } from '@nestjs/core/helpers/execution-context-host';

@Injectable()
export class AuthenticatedUserAuthGuard extends AuthGuard implements CanActivate {
    constructor(
        @Inject(KEYCLOAK_INSTANCE)
        private keycloak1: any,
        @Inject(KEYCLOAK_CONNECT_OPTIONS)
        private keycloakOpts1: any,
        @Inject(KEYCLOAK_LOGGER)
        private logger1: Logger,
        private readonly reflector1: Reflector, // //private readonly keycloakAdminService: KeycloakAdminService,
    ) {
        super(keycloak1, keycloakOpts1, logger1, reflector1);
    }

    async canActivate(context: ExecutionContext): Promise<boolean> {
        const value = super.canActivate(context);
        const [request] = extractRequest(context);
        //const tokenUserId = request.user.sub;

        //const authenticatedUser = await this.keycloakAdminService.findById(tokenUserId);
        //request.authenticatedUser = authenticatedUser;
        return value;
    }
}

export class AuthenticatedGraphQLUserGuard extends AuthenticatedUserAuthGuard {
    canActivate(context: ExecutionContext) {
        const ctx = GqlExecutionContext.create(context);
        const { req } = ctx.getContext();
        return super.canActivate(new ExecutionContextHost([req]));
    }
}

export function UseAuthenticatedGraphQLUserGuard(userRoles: string[]) {
    return applyDecorators(
        Roles({ roles: userRoles, mode: RoleMatchingMode.ANY }),
        UseGuards(AuthenticatedGraphQLUserGuard),
    );
}
```

Which I try to use by placing the following code alongside my @Query dectorator.
```
 @UseAuthenticatedGraphQLUserGuard([UserRoles.ADMIN, UserRoles.SUPPORT, UserRoles.RETAILER])
```

This gives me the following error:
```
[Nest] 39654   - 08/31/2021, 3:23:38 PM   [ExceptionsHandler]  +0ms
TypeError
    at Object.getMetadata (/Users/snip/Documents/GitHub/backend/node_modules/reflect-metadata/Reflect.js:354:23)
    at /Users/snip/Documents/GitHub/backend/node_modules/@nestjs/core/services/reflector.service.js:34:54
    at Array.map (<anonymous>)
    at Reflector.getAll (/Users/snip/Documents/GitHub/backend/node_modules/@nestjs/core/services/reflector.service.js:34:32)
    at Reflector.getAllAndOverride (/Users/snip/Documents/GitHub/backend/node_modules/@nestjs/core/services/reflector.service.js:66:41)
    at AuthenticatedGraphQLUserGuard.<anonymous> (/Users/snip/Documents/GitHub/backend/node_modules/nest-keycloak-connect/guards/auth.guard.js:64:50)
    at Generator.next (<anonymous>)
    at /Users/snip/Documents/GitHub/backend/node_modules/nest-keycloak-connect/guards/auth.guard.js:39:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/snip/Documents/GitHub/backend/node_modules/nest-keycloak-connect/guards/auth.guard.js:35:12)
```

As you can see here, I have commented out everything not related to the issue, and it still appears.

**Comment by ashleyww93** [comment]
I hadn't imported the Module. My Mistake :)

**Comment by ferrerojosh** [comment]
I am confused by this, if you're extending AuthGuard, you should be using your extended AuthGuard on your AppModule, since all it does is extract the request, attach the user and token into it, and throw unauthorized if necessary.

I will try to try creating an extended AuthGuard on my own, and see if it works fine on my end when I have free time.
