### ISSUE TITLE
Using a string to reference a keycloak json config doesn't work for relative paths

### ISSUE THREAD

**Issue by diogomoreira** [ferrerojosh/nest-keycloak-connect#90]
## Current behavior

I tried to configure the KeycloakModule using `KeycloakConnectModule.register('assets/keycloak.json')` in a file that is inside `apps/main-ms/src/modules/security/`, but it's not working, as the file is expected to be in the root of the project. The error stack is:

```
Error: ENOENT: no such file or directory, open '/Users/diogomoreira/Development/project/keycloak.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at parseConfig (/Users/diogomoreira/Development/project/node_modules/nest-keycloak-connect/keycloak-connect.providers.js:73:25)
    at Object.createKeycloakConnectOptionProvider (/Users/diogomoreira/Development/project/node_modules/nest-keycloak-connect/keycloak-connect.providers.js:82:19)
    at Function.register (/Users/diogomoreira/Development/project/node_modules/nest-keycloak-connect/keycloak-connect.module.js:55:42)
    at Object../apps/main-ms/src/modules/security/security.module.ts (/Users/diogomoreira/Development/project/dist/apps/main-ms/webpack:/apps/main-ms/src/modules/security/security.module.ts:8:35)
    at __webpack_require__ (/Users/diogomoreira/Development/project/dist/apps/main-ms/webpack:/webpack/bootstrap:19:1)
    at Object../apps/main-ms/src/modules/app.module.ts (/Users/diogomoreira/Development/project/dist/apps/main-ms/webpack:/apps/main-ms/src/modules/app.module.ts:6:1)
    at __webpack_require__ (/Users/diogomoreira/Development/project/dist/apps/main-ms/webpack:/webpack/bootstrap:19:1)
    at Object../apps/main-ms/src/main.ts (/Users/diogomoreira/Development/project/dist/apps/main-ms/webpack:/apps/main-ms/src/main.ts:5:1)
```
Since I'm working on a monorepo (using NX) and I have two modules that uses `nest-keycloak-connect`, I need to have two `keycloak.json` in the root of the project, which is not desirable in this situation.

## Expected behavior

It should be accepted relative paths for keycloak config.

Taking a look at the `keycloak-connect.providers.ts` (code below), I saw that it uses `process.cwd()` to get the path for the file, which takes the path from which I invoked the command to run the application. 

```
const parseConfig = (
  opts: KeycloakConnectOptions,
  config?: NestKeycloakConfig,
): KeycloakConnectConfig => {
  if (typeof opts === 'string') {
    const configPath = path.join(process.cwd(), opts);
    const json = fs.readFileSync(configPath);
    const keycloakConfig = JSON.parse(json.toString());
    return Object.assign(keycloakConfig, config);
  }
  return opts;
};
```
Shouldn't it be using `__dirname` instead? I guess in this way, we could use relative paths for configuration.

**Comment by ferrerojosh** [comment]
I'll add a check for both relative and cwd path. With relative path on the higher priority. This way it won't break for existing users who puts keycloak.json on their root.
