### ISSUE TITLE
Incorrect Keycloak Realm in example/nest-example.json

### ISSUE THREAD

**Issue by sreenath-n** [ferrerojosh/nest-keycloak-connect#97]
Getting error when importing `example/nest-example.json`

```
14:35:14,124 WARN  [org.keycloak.services] (ServerService Thread Pool -- 70) KC-SERVICES0005: Unable to import realm nest-example from file /tmp/nest-example.json.: java.lang.RuntimeException: Invalid client account-console: Base URL is not a valid URL; A redirect URI is not a valid URI
	at org.keycloak.keycloak-server-spi-private@15.0.2//org.keycloak.models.utils.RepresentationToModel.lambda$createClients$7(RepresentationToModel.java:1346)
	at org.keycloak.keycloak-server-spi-private@15.0.2//org.keycloak.validation.ValidationUtil.validateClient(ValidationUtil.java:45)
	at org.keycloak.keycloak-server-spi-private@15.0.2//org.keycloak.validation.ValidationUtil.validateClient(ValidationUtil.java:28)
	at org.keycloak.keycloak-server-spi-private@15.0.2//org.keycloak.models.utils.RepresentationToModel.createClients(RepresentationToModel.java:1345)
	at org.keycloak.keycloak-server-spi-private@15.0.2//org.keycloak.models.utils.RepresentationToModel.importRealm(RepresentationToModel.java:350)
	at org.keycloak.keycloak-services@15.0.2//org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:557)

```
I am using Keycloak docker to load the json
```
docker run -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin \
    -e KEYCLOAK_IMPORT=/tmp/nest-example.json -v $(pwd)/nest-example.json:/tmp/nest-example.json jboss/keycloak
```

Are these below URLs correct?

![image](https://user-images.githubusercontent.com/69649218/145591861-2f80980b-56c5-420a-9340-7bb565e59fe7.png)

**Comment by ferrerojosh** [comment]
Well that is strange, I guess they use the display name during export

**Comment by sreenath-n** [comment]
@ferrerojosh This is not resolved. Another error is coming when I ran it using the new json from d215763
```
04:20:43,429 WARN  [org.keycloak.services] (ServerService Thread Pool -- 66) KC-SERVICES0005: Unable to import realm nest-example from file /tmp/nest-example.json.: java.lang.RuntimeException: Error while updating policy [User Policy]. User [user] could not be found.
	at org.keycloak.keycloak-authz-policy-common@15.0.2//org.keycloak.authorization.policy.provider.user.UserPolicyProviderFactory.updateUsers(UserPolicyProviderFactory.java:147)
	at org.keycloak.keycloak-authz-policy-common@15.0.2//org.keycloak.authorization.policy.provider.user.UserPolicyProviderFactory.onImport(UserPolicyProviderFactory.java:100)
	at org.keycloak.keycloak-server-spi-private@15.0.2//org.keycloak.models.utils.RepresentationToModel.toModel(RepresentationToModel.java:2466)
	at org.keycloak.keycloak-server-spi-private@15.0.2//org.keycloak.authorization.AuthorizationProvider$3.create(AuthorizationProvider.java:351)
```

Looks like the users "user" and "admin", that are mentioned under policy, are not there in the json

**Comment by ferrerojosh** [comment]
> @ferrerojosh This is not resolved. Another error is coming when I ran it using the new json from [d215763](https://github.com/ferrerojosh/nest-keycloak-connect/commit/d2157636df2f0064efaf6d9a46601c3a2c4e6ef8)
> 
> ```
> 04:20:43,429 WARN  [org.keycloak.services] (ServerService Thread Pool -- 66) KC-SERVICES0005: Unable to import realm nest-example from file /tmp/nest-example.json.: java.lang.RuntimeException: Error while updating policy [User Policy]. User [user] could not be found.
> 	at org.keycloak.keycloak-authz-policy-common@15.0.2//org.keycloak.authorization.policy.provider.user.UserPolicyProviderFactory.updateUsers(UserPolicyProviderFactory.java:147)
> 	at org.keycloak.keycloak-authz-policy-common@15.0.2//org.keycloak.authorization.policy.provider.user.UserPolicyProviderFactory.onImport(UserPolicyProviderFactory.java:100)
> 	at org.keycloak.keycloak-server-spi-private@15.0.2//org.keycloak.models.utils.RepresentationToModel.toModel(RepresentationToModel.java:2466)
> 	at org.keycloak.keycloak-server-spi-private@15.0.2//org.keycloak.authorization.AuthorizationProvider$3.create(AuthorizationProvider.java:351)
> ```
> 
> Looks like the users "user" and "admin", that are mentioned under policy, are not there in the json

It looked like you need to create these users, but again since this is an import, there should be a way to include the users in the json file, and here I thought Keycloak realm exports included them. I do not know much how these exports work since I'm no Keycloak expert. I will have to consult the documentation again.

**Comment by ferrerojosh** [comment]
Okay looks like there is another way of exporting using the keycloak command line.

**Comment by sreenath-n** [comment]
Now import is working perfectly. Thanks @ferrerojosh 

**Note:** `upload_scripts` must be enabled in Keycloak, for example, using this parameter `keycloak.profile.feature.upload_scripts=enabled`
Otherwise Keycloak will throw error when importing.
